FROM armindocachada/tensorflow-raspberrypi

RUN mkdir -p /data/videos/incoming
#RUN chmod u+x  /etc/init.d/intruder_detection_service
COPY scripts/intruder_detection_service.sh /etc/init.d/intruder_detection_service
COPY python /intruder-detector/
COPY credentials /intruder-detector/credentials

WORKDIR /intruder-detector

COPY scripts/start.sh /root/start.sh
ENTRYPOINT ["/root/start.sh"]