FROM tensorflow/tensorflow:1.12.0-devel-py3

RUN apt-get update
RUN apt-get -y install wget
RUN apt-get update
RUN apt-get -y install libv4l-dev
RUN apt-get -y install libavcodec-dev libavformat-dev libavdevice-dev
RUN apt-get -y install cmake
#RUN apt-get -y install python-opencv
RUN apt-get -y install ffmpeg

WORKDIR /root
RUN wget https://github.com/opencv/opencv/archive/3.4.4.zip
RUN unzip -o 3.4.4.zip
WORKDIR /root/opencv-3.4.4/build
RUN cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local  -D WITH_FFMPEG=ON -D WITH_TBB=ON -D WITH_GTK=ON -D WITH_V4L=ON -D WITH_OPENGL=ON -D WITH_CUBLAS=ON -DWITH_QT=OFF -DCUDA_NVCC_FLAGS="-D_FORCE_INLINES" ..
RUN make -j7
RUN make install


RUN apt-get -y install python3-matplotlib python3-tk
RUN pip3 install ephem
RUN pip3 install Cython jupyter slackclient
RUN pip3 install pillow lxml
RUN pip3 install imutils
RUN pip3 uninstall -y matplotlib
#RUN pip3 install opencv-python
RUN pip3 install opencv-contrib-python
RUN mkdir -p /tensorflow
WORKDIR /tensorflow
RUN git clone https://github.com/armindocachada/models
RUN curl -OL https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip
RUN unzip -o protoc-3.6.1-linux-x86_64.zip -d /usr/local bin/protoc
RUN cd /tensorflow/models/research && protoc object_detection/protos/*.proto --python_out=.
RUN cd /tensorflow/models/research && export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim && python3 object_detection/builders/model_builder_test.py
RUN echo 'cd /tensorflow/models/research && export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim':`pwd`/object_detection >> /root/.bashrc

RUN apt-get install -y libsm6 libxext6